//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/catalogs", ConfigurationName="CatalogsPort")]
public interface CatalogsPort
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<AddProductToCatalogResponse1> AddProductToCatalogAsync(AddProductToCatalogRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<ExportCatalogToPdfResponse1> ExportCatalogToPdfAsync(ExportCatalogToPdfRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateCatalogResponse1> CreateCatalogAsync(CreateCatalogRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<DeleteCatalogResponse1> DeleteCatalogAsync(DeleteCatalogRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<GetCatalogByIdResponse1> GetCatalogByIdAsync(GetCatalogByIdRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class AddProductToCatalogRequest
{
    
    private long catalogIdField;
    
    private string productCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long catalogId
    {
        get
        {
            return this.catalogIdField;
        }
        set
        {
            this.catalogIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string productCode
    {
        get
        {
            return this.productCodeField;
        }
        set
        {
            this.productCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/catalogs")]
public partial class SoapProduct
{
    
    private string codeField;
    
    private string nameField;
    
    private string sizeField;
    
    private string colorField;
    
    private bool activeField;
    
    private string photoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string color
    {
        get
        {
            return this.colorField;
        }
        set
        {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string photo
    {
        get
        {
            return this.photoField;
        }
        set
        {
            this.photoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/catalogs")]
public partial class SoapCatalog
{
    
    private long idField;
    
    private string nameField;
    
    private SoapProduct[] productsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("products", Order=2)]
    public SoapProduct[] products
    {
        get
        {
            return this.productsField;
        }
        set
        {
            this.productsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class AddProductToCatalogResponse
{
    
    private SoapCatalog catalogField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SoapCatalog catalog
    {
        get
        {
            return this.catalogField;
        }
        set
        {
            this.catalogField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AddProductToCatalogRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public AddProductToCatalogRequest AddProductToCatalogRequest;
    
    public AddProductToCatalogRequest1()
    {
    }
    
    public AddProductToCatalogRequest1(AddProductToCatalogRequest AddProductToCatalogRequest)
    {
        this.AddProductToCatalogRequest = AddProductToCatalogRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AddProductToCatalogResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public AddProductToCatalogResponse AddProductToCatalogResponse;
    
    public AddProductToCatalogResponse1()
    {
    }
    
    public AddProductToCatalogResponse1(AddProductToCatalogResponse AddProductToCatalogResponse)
    {
        this.AddProductToCatalogResponse = AddProductToCatalogResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class ExportCatalogToPdfRequest
{
    
    private long catalogIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long catalogId
    {
        get
        {
            return this.catalogIdField;
        }
        set
        {
            this.catalogIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class ExportCatalogToPdfResponse
{
    
    private string statusField;
    
    private string pdfUrlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string pdfUrl
    {
        get
        {
            return this.pdfUrlField;
        }
        set
        {
            this.pdfUrlField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ExportCatalogToPdfRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public ExportCatalogToPdfRequest ExportCatalogToPdfRequest;
    
    public ExportCatalogToPdfRequest1()
    {
    }
    
    public ExportCatalogToPdfRequest1(ExportCatalogToPdfRequest ExportCatalogToPdfRequest)
    {
        this.ExportCatalogToPdfRequest = ExportCatalogToPdfRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ExportCatalogToPdfResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public ExportCatalogToPdfResponse ExportCatalogToPdfResponse;
    
    public ExportCatalogToPdfResponse1()
    {
    }
    
    public ExportCatalogToPdfResponse1(ExportCatalogToPdfResponse ExportCatalogToPdfResponse)
    {
        this.ExportCatalogToPdfResponse = ExportCatalogToPdfResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class CreateCatalogRequest
{
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class CreateCatalogResponse
{
    
    private SoapCatalog catalogField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SoapCatalog catalog
    {
        get
        {
            return this.catalogField;
        }
        set
        {
            this.catalogField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateCatalogRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public CreateCatalogRequest CreateCatalogRequest;
    
    public CreateCatalogRequest1()
    {
    }
    
    public CreateCatalogRequest1(CreateCatalogRequest CreateCatalogRequest)
    {
        this.CreateCatalogRequest = CreateCatalogRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateCatalogResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public CreateCatalogResponse CreateCatalogResponse;
    
    public CreateCatalogResponse1()
    {
    }
    
    public CreateCatalogResponse1(CreateCatalogResponse CreateCatalogResponse)
    {
        this.CreateCatalogResponse = CreateCatalogResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class DeleteCatalogRequest
{
    
    private long catalogIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long catalogId
    {
        get
        {
            return this.catalogIdField;
        }
        set
        {
            this.catalogIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class DeleteCatalogResponse
{
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DeleteCatalogRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public DeleteCatalogRequest DeleteCatalogRequest;
    
    public DeleteCatalogRequest1()
    {
    }
    
    public DeleteCatalogRequest1(DeleteCatalogRequest DeleteCatalogRequest)
    {
        this.DeleteCatalogRequest = DeleteCatalogRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DeleteCatalogResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public DeleteCatalogResponse DeleteCatalogResponse;
    
    public DeleteCatalogResponse1()
    {
    }
    
    public DeleteCatalogResponse1(DeleteCatalogResponse DeleteCatalogResponse)
    {
        this.DeleteCatalogResponse = DeleteCatalogResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class GetCatalogByIdRequest
{
    
    private long catalogIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long catalogId
    {
        get
        {
            return this.catalogIdField;
        }
        set
        {
            this.catalogIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/catalogs")]
public partial class GetCatalogByIdResponse
{
    
    private SoapCatalog catalogField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SoapCatalog catalog
    {
        get
        {
            return this.catalogField;
        }
        set
        {
            this.catalogField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCatalogByIdRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public GetCatalogByIdRequest GetCatalogByIdRequest;
    
    public GetCatalogByIdRequest1()
    {
    }
    
    public GetCatalogByIdRequest1(GetCatalogByIdRequest GetCatalogByIdRequest)
    {
        this.GetCatalogByIdRequest = GetCatalogByIdRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCatalogByIdResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/catalogs", Order=0)]
    public GetCatalogByIdResponse GetCatalogByIdResponse;
    
    public GetCatalogByIdResponse1()
    {
    }
    
    public GetCatalogByIdResponse1(GetCatalogByIdResponse GetCatalogByIdResponse)
    {
        this.GetCatalogByIdResponse = GetCatalogByIdResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
public interface CatalogsPortChannel : CatalogsPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
public partial class CatalogsPortClient : System.ServiceModel.ClientBase<CatalogsPort>, CatalogsPort
{
    
    /// <summary>
    /// Implemente este método parcial para configurar el punto de conexión de servicio.
    /// </summary>
    /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
    /// <param name="clientCredentials">Credenciales de cliente</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public CatalogsPortClient() : 
            base(CatalogsPortClient.GetDefaultBinding(), CatalogsPortClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.CatalogsPortSoap11.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CatalogsPortClient(EndpointConfiguration endpointConfiguration) : 
            base(CatalogsPortClient.GetBindingForEndpoint(endpointConfiguration), CatalogsPortClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CatalogsPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(CatalogsPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CatalogsPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(CatalogsPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CatalogsPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<AddProductToCatalogResponse1> CatalogsPort.AddProductToCatalogAsync(AddProductToCatalogRequest1 request)
    {
        return base.Channel.AddProductToCatalogAsync(request);
    }
    
    public System.Threading.Tasks.Task<AddProductToCatalogResponse1> AddProductToCatalogAsync(AddProductToCatalogRequest AddProductToCatalogRequest)
    {
        AddProductToCatalogRequest1 inValue = new AddProductToCatalogRequest1();
        inValue.AddProductToCatalogRequest = AddProductToCatalogRequest;
        return ((CatalogsPort)(this)).AddProductToCatalogAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ExportCatalogToPdfResponse1> CatalogsPort.ExportCatalogToPdfAsync(ExportCatalogToPdfRequest1 request)
    {
        return base.Channel.ExportCatalogToPdfAsync(request);
    }
    
    public System.Threading.Tasks.Task<ExportCatalogToPdfResponse1> ExportCatalogToPdfAsync(ExportCatalogToPdfRequest ExportCatalogToPdfRequest)
    {
        ExportCatalogToPdfRequest1 inValue = new ExportCatalogToPdfRequest1();
        inValue.ExportCatalogToPdfRequest = ExportCatalogToPdfRequest;
        return ((CatalogsPort)(this)).ExportCatalogToPdfAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateCatalogResponse1> CatalogsPort.CreateCatalogAsync(CreateCatalogRequest1 request)
    {
        return base.Channel.CreateCatalogAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateCatalogResponse1> CreateCatalogAsync(CreateCatalogRequest CreateCatalogRequest)
    {
        CreateCatalogRequest1 inValue = new CreateCatalogRequest1();
        inValue.CreateCatalogRequest = CreateCatalogRequest;
        return ((CatalogsPort)(this)).CreateCatalogAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<DeleteCatalogResponse1> CatalogsPort.DeleteCatalogAsync(DeleteCatalogRequest1 request)
    {
        return base.Channel.DeleteCatalogAsync(request);
    }
    
    public System.Threading.Tasks.Task<DeleteCatalogResponse1> DeleteCatalogAsync(DeleteCatalogRequest DeleteCatalogRequest)
    {
        DeleteCatalogRequest1 inValue = new DeleteCatalogRequest1();
        inValue.DeleteCatalogRequest = DeleteCatalogRequest;
        return ((CatalogsPort)(this)).DeleteCatalogAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetCatalogByIdResponse1> CatalogsPort.GetCatalogByIdAsync(GetCatalogByIdRequest1 request)
    {
        return base.Channel.GetCatalogByIdAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetCatalogByIdResponse1> GetCatalogByIdAsync(GetCatalogByIdRequest GetCatalogByIdRequest)
    {
        GetCatalogByIdRequest1 inValue = new GetCatalogByIdRequest1();
        inValue.GetCatalogByIdRequest = GetCatalogByIdRequest;
        return ((CatalogsPort)(this)).GetCatalogByIdAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.CatalogsPortSoap11))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.CatalogsPortSoap11))
        {
            return new System.ServiceModel.EndpointAddress("http://localhost:8080/ws/*");
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return CatalogsPortClient.GetBindingForEndpoint(EndpointConfiguration.CatalogsPortSoap11);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return CatalogsPortClient.GetEndpointAddress(EndpointConfiguration.CatalogsPortSoap11);
    }
    
    public enum EndpointConfiguration
    {
        
        CatalogsPortSoap11,
    }
}
