//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/purchase_orders", ConfigurationName="PurchaseOrderPort")]
public interface PurchaseOrderPort
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<SearchPurchaseOrdersResponse> SearchPurchaseOrdersAsync(SearchPurchaseOrdersRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/purchase_orders")]
public partial class SearchPurchaseOrdersRequest
{
    
    private string productCodeField;
    
    private string startRequestDateField;
    
    private string endRequestDateField;
    
    private string statusField;
    
    private string storeCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string productCode
    {
        get
        {
            return this.productCodeField;
        }
        set
        {
            this.productCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string startRequestDate
    {
        get
        {
            return this.startRequestDateField;
        }
        set
        {
            this.startRequestDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string endRequestDate
    {
        get
        {
            return this.endRequestDateField;
        }
        set
        {
            this.endRequestDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string storeCode
    {
        get
        {
            return this.storeCodeField;
        }
        set
        {
            this.storeCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/purchase_orders")]
public partial class OrderItemSoap
{
    
    private string codeField;
    
    private int quantityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int quantity
    {
        get
        {
            return this.quantityField;
        }
        set
        {
            this.quantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/purchase_orders")]
public partial class PurchaseOrderSoap
{
    
    private int idPurchaseOrderField;
    
    private string stateField;
    
    private string observationsField;
    
    private string requestDateField;
    
    private string receiptDateField;
    
    private string storeCodeField;
    
    private OrderItemSoap[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int idPurchaseOrder
    {
        get
        {
            return this.idPurchaseOrderField;
        }
        set
        {
            this.idPurchaseOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string observations
    {
        get
        {
            return this.observationsField;
        }
        set
        {
            this.observationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string requestDate
    {
        get
        {
            return this.requestDateField;
        }
        set
        {
            this.requestDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string receiptDate
    {
        get
        {
            return this.receiptDateField;
        }
        set
        {
            this.receiptDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string storeCode
    {
        get
        {
            return this.storeCodeField;
        }
        set
        {
            this.storeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("items", Order=6)]
    public OrderItemSoap[] items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SearchPurchaseOrdersRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/purchase_orders", Order=0)]
    public SearchPurchaseOrdersRequest SearchPurchaseOrdersRequest;
    
    public SearchPurchaseOrdersRequest1()
    {
    }
    
    public SearchPurchaseOrdersRequest1(SearchPurchaseOrdersRequest SearchPurchaseOrdersRequest)
    {
        this.SearchPurchaseOrdersRequest = SearchPurchaseOrdersRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SearchPurchaseOrdersResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPurchaseOrdersResponse", Namespace="http://soap/purchase_orders", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("purchaseOrders", IsNullable=false)]
    public PurchaseOrderSoap[] SearchPurchaseOrdersResponse1;
    
    public SearchPurchaseOrdersResponse()
    {
    }
    
    public SearchPurchaseOrdersResponse(PurchaseOrderSoap[] SearchPurchaseOrdersResponse1)
    {
        this.SearchPurchaseOrdersResponse1 = SearchPurchaseOrdersResponse1;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface PurchaseOrderPortChannel : PurchaseOrderPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class PurchaseOrderPortClient : System.ServiceModel.ClientBase<PurchaseOrderPort>, PurchaseOrderPort
{
    
    /// <summary>
    /// Implemente este método parcial para configurar el punto de conexión de servicio.
    /// </summary>
    /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
    /// <param name="clientCredentials">Credenciales de cliente</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public PurchaseOrderPortClient() : 
            base(PurchaseOrderPortClient.GetDefaultBinding(), PurchaseOrderPortClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.PurchaseOrderPortSoap11.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PurchaseOrderPortClient(EndpointConfiguration endpointConfiguration) : 
            base(PurchaseOrderPortClient.GetBindingForEndpoint(endpointConfiguration), PurchaseOrderPortClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PurchaseOrderPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(PurchaseOrderPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PurchaseOrderPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(PurchaseOrderPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PurchaseOrderPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SearchPurchaseOrdersResponse> PurchaseOrderPort.SearchPurchaseOrdersAsync(SearchPurchaseOrdersRequest1 request)
    {
        return base.Channel.SearchPurchaseOrdersAsync(request);
    }
    
    public System.Threading.Tasks.Task<SearchPurchaseOrdersResponse> SearchPurchaseOrdersAsync(SearchPurchaseOrdersRequest SearchPurchaseOrdersRequest)
    {
        SearchPurchaseOrdersRequest1 inValue = new SearchPurchaseOrdersRequest1();
        inValue.SearchPurchaseOrdersRequest = SearchPurchaseOrdersRequest;
        return ((PurchaseOrderPort)(this)).SearchPurchaseOrdersAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PurchaseOrderPortSoap11))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PurchaseOrderPortSoap11))
        {
            return new System.ServiceModel.EndpointAddress("http://localhost:8080/ws/*");
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return PurchaseOrderPortClient.GetBindingForEndpoint(EndpointConfiguration.PurchaseOrderPortSoap11);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return PurchaseOrderPortClient.GetEndpointAddress(EndpointConfiguration.PurchaseOrderPortSoap11);
    }
    
    public enum EndpointConfiguration
    {
        
        PurchaseOrderPortSoap11,
    }
}
