//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/filters", ConfigurationName="FilterPort")]
public interface FilterPort
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<GetFiltersByUserResponse> GetFiltersByUserAsync(GetFiltersByUserRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<SaveFilterResponse1> SaveFilterAsync(SaveFilterRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<DeleteFilterResponse1> DeleteFilterAsync(DeleteFilterRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/filters")]
public partial class GetFiltersByUserRequest
{
    
    private int userField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int user
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap/filters")]
public partial class FilterSoap
{
    
    private long idField;
    
    private int userField;
    
    private string nameField;
    
    private string filtersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int user
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string filters
    {
        get
        {
            return this.filtersField;
        }
        set
        {
            this.filtersField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetFiltersByUserRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/filters", Order=0)]
    public GetFiltersByUserRequest GetFiltersByUserRequest;
    
    public GetFiltersByUserRequest1()
    {
    }
    
    public GetFiltersByUserRequest1(GetFiltersByUserRequest GetFiltersByUserRequest)
    {
        this.GetFiltersByUserRequest = GetFiltersByUserRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetFiltersByUserResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFiltersByUserResponse", Namespace="http://soap/filters", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("filters", IsNullable=false)]
    public FilterSoap[] GetFiltersByUserResponse1;
    
    public GetFiltersByUserResponse()
    {
    }
    
    public GetFiltersByUserResponse(FilterSoap[] GetFiltersByUserResponse1)
    {
        this.GetFiltersByUserResponse1 = GetFiltersByUserResponse1;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/filters")]
public partial class SaveFilterRequest
{
    
    private FilterSoap filterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FilterSoap filter
    {
        get
        {
            return this.filterField;
        }
        set
        {
            this.filterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/filters")]
public partial class SaveFilterResponse
{
    
    private FilterSoap filterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FilterSoap filter
    {
        get
        {
            return this.filterField;
        }
        set
        {
            this.filterField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SaveFilterRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/filters", Order=0)]
    public SaveFilterRequest SaveFilterRequest;
    
    public SaveFilterRequest1()
    {
    }
    
    public SaveFilterRequest1(SaveFilterRequest SaveFilterRequest)
    {
        this.SaveFilterRequest = SaveFilterRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SaveFilterResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/filters", Order=0)]
    public SaveFilterResponse SaveFilterResponse;
    
    public SaveFilterResponse1()
    {
    }
    
    public SaveFilterResponse1(SaveFilterResponse SaveFilterResponse)
    {
        this.SaveFilterResponse = SaveFilterResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/filters")]
public partial class DeleteFilterRequest
{
    
    private long filterIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long filterId
    {
        get
        {
            return this.filterIdField;
        }
        set
        {
            this.filterIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap/filters")]
public partial class DeleteFilterResponse
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DeleteFilterRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/filters", Order=0)]
    public DeleteFilterRequest DeleteFilterRequest;
    
    public DeleteFilterRequest1()
    {
    }
    
    public DeleteFilterRequest1(DeleteFilterRequest DeleteFilterRequest)
    {
        this.DeleteFilterRequest = DeleteFilterRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DeleteFilterResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap/filters", Order=0)]
    public DeleteFilterResponse DeleteFilterResponse;
    
    public DeleteFilterResponse1()
    {
    }
    
    public DeleteFilterResponse1(DeleteFilterResponse DeleteFilterResponse)
    {
        this.DeleteFilterResponse = DeleteFilterResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface FilterPortChannel : FilterPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class FilterPortClient : System.ServiceModel.ClientBase<FilterPort>, FilterPort
{
    
    /// <summary>
    /// Implemente este método parcial para configurar el punto de conexión de servicio.
    /// </summary>
    /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
    /// <param name="clientCredentials">Credenciales de cliente</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public FilterPortClient() : 
            base(FilterPortClient.GetDefaultBinding(), FilterPortClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.FilterPortSoap11.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public FilterPortClient(EndpointConfiguration endpointConfiguration) : 
            base(FilterPortClient.GetBindingForEndpoint(endpointConfiguration), FilterPortClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public FilterPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(FilterPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public FilterPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(FilterPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public FilterPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetFiltersByUserResponse> FilterPort.GetFiltersByUserAsync(GetFiltersByUserRequest1 request)
    {
        return base.Channel.GetFiltersByUserAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetFiltersByUserResponse> GetFiltersByUserAsync(GetFiltersByUserRequest GetFiltersByUserRequest)
    {
        GetFiltersByUserRequest1 inValue = new GetFiltersByUserRequest1();
        inValue.GetFiltersByUserRequest = GetFiltersByUserRequest;
        return ((FilterPort)(this)).GetFiltersByUserAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SaveFilterResponse1> FilterPort.SaveFilterAsync(SaveFilterRequest1 request)
    {
        return base.Channel.SaveFilterAsync(request);
    }
    
    public System.Threading.Tasks.Task<SaveFilterResponse1> SaveFilterAsync(SaveFilterRequest SaveFilterRequest)
    {
        SaveFilterRequest1 inValue = new SaveFilterRequest1();
        inValue.SaveFilterRequest = SaveFilterRequest;
        return ((FilterPort)(this)).SaveFilterAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<DeleteFilterResponse1> FilterPort.DeleteFilterAsync(DeleteFilterRequest1 request)
    {
        return base.Channel.DeleteFilterAsync(request);
    }
    
    public System.Threading.Tasks.Task<DeleteFilterResponse1> DeleteFilterAsync(DeleteFilterRequest DeleteFilterRequest)
    {
        DeleteFilterRequest1 inValue = new DeleteFilterRequest1();
        inValue.DeleteFilterRequest = DeleteFilterRequest;
        return ((FilterPort)(this)).DeleteFilterAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.FilterPortSoap11))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.FilterPortSoap11))
        {
            return new System.ServiceModel.EndpointAddress("http://localhost:8080/ws/*");
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return FilterPortClient.GetBindingForEndpoint(EndpointConfiguration.FilterPortSoap11);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return FilterPortClient.GetEndpointAddress(EndpointConfiguration.FilterPortSoap11);
    }
    
    public enum EndpointConfiguration
    {
        
        FilterPortSoap11,
    }
}
